/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libraries;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bachiecam
 */




public class ApplicationForm extends javax.swing.JFrame {

  
     Connection con = null;
     PreparedStatement pat = null;
     ResultSet rs = null;
     
    /**
     * Creates new form ApplicationForm
     */
    public ApplicationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JTextFieldFirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        BirthPlace = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        CivilStatus = new javax.swing.JTextField();
        YesPrior = new javax.swing.JRadioButton();
        NoPrior = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        GenderFemale = new javax.swing.JRadioButton();
        GenderMale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quarantine Pass Application");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Futura BdCn BT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PassKaNa |");

        jLabel2.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GUSTO MO GALA? TARA NA!");

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(1238, 1238, 1238))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(494, 494, 494))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel3.setText("LAST NAME");

        jLabel13.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel13.setText("FIRST NAME");

        jLabel14.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel14.setText("MIDDLE NAME");

        jLabel15.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel15.setText("BIRTHPLACE");

        jLabel16.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel16.setText("PHONE NUMBER");

        jLabel17.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel17.setText("CIVIL STATUS");

        jLabel18.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel18.setText("GENDER");

        jLabel19.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel19.setText("PRIOR APPLICATION");

        jLabel20.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        jLabel20.setText("AGE");

        JTextFieldFirstName.setBackground(new java.awt.Color(204, 204, 204));
        JTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldFirstNameActionPerformed(evt);
            }
        });

        LastName.setBackground(new java.awt.Color(204, 204, 204));
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        MiddleName.setBackground(new java.awt.Color(204, 204, 204));
        MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameActionPerformed(evt);
            }
        });

        BirthPlace.setBackground(new java.awt.Color(204, 204, 204));
        BirthPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthPlaceActionPerformed(evt);
            }
        });

        PhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });

        Age.setBackground(new java.awt.Color(204, 204, 204));
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        CivilStatus.setBackground(new java.awt.Color(204, 204, 204));
        CivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivilStatusActionPerformed(evt);
            }
        });

        YesPrior.setBackground(new java.awt.Color(51, 51, 51));
        YesPrior.setFont(new java.awt.Font("Futura BdCn BT", 0, 18)); // NOI18N
        YesPrior.setText("YES");
        YesPrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesPriorActionPerformed(evt);
            }
        });

        NoPrior.setBackground(new java.awt.Color(51, 51, 51));
        NoPrior.setFont(new java.awt.Font("Futura BdCn BT", 0, 18)); // NOI18N
        NoPrior.setText("NO");
        NoPrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoPriorActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(145, 25, 36));
        clearButton.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        submitButton1.setBackground(new java.awt.Color(0, 192, 96));
        submitButton1.setFont(new java.awt.Font("Futura BdCn BT", 0, 24)); // NOI18N
        submitButton1.setText("SUBMIT");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        GenderFemale.setBackground(new java.awt.Color(51, 51, 51));
        GenderFemale.setFont(new java.awt.Font("Futura BdCn BT", 0, 18)); // NOI18N
        GenderFemale.setText("FEMALE");
        GenderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderFemaleActionPerformed(evt);
            }
        });

        GenderMale.setBackground(new java.awt.Color(51, 51, 51));
        GenderMale.setFont(new java.awt.Font("Futura BdCn BT", 0, 18)); // NOI18N
        GenderMale.setText("MALE");
        GenderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderMaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CivilStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(Age, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(YesPrior)
                                .addGap(41, 41, 41)
                                .addComponent(NoPrior))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GenderMale)
                                .addGap(18, 18, 18)
                                .addComponent(GenderFemale)))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(submitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(485, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextFieldFirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15))
                                    .addComponent(BirthPlace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addComponent(PhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addComponent(CivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(GenderFemale)
                    .addComponent(GenderMale))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(YesPrior)
                    .addComponent(NoPrior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(542, Short.MAX_VALUE)
                    .addComponent(submitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(220, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(666, 666, 666))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void JTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldFirstNameActionPerformed

    private void MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleNameActionPerformed

    private void BirthPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthPlaceActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void CivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CivilStatusActionPerformed

    private void YesPriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesPriorActionPerformed
        if (YesPrior.isSelected()) {
            NoPrior.setSelected(false);
        }
    }//GEN-LAST:event_YesPriorActionPerformed

    private void NoPriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoPriorActionPerformed
        if (NoPrior.isSelected()) {
            YesPrior.setSelected(false);
        }
    }//GEN-LAST:event_NoPriorActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        JTextFieldFirstName.setText(null);
        LastName.setText(null);
        MiddleName.setText(null);
        BirthPlace.setText(null);
        PhoneNumber.setText(null);
        Age.setText(null);
        CivilStatus.setText(null);
        GenderFemale.setSelected(false);
        GenderMale.setSelected(false);
        YesPrior.setSelected(false);
        NoPrior.setSelected(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
       
        String firstName = JTextFieldFirstName.getText();
        String lastName = LastName.getText();
        String middleName = MiddleName.getText();
        String birthPlace= BirthPlace.getText();
        String phoneNumber = PhoneNumber.getText();
        String age = Age.getText();
        String civilStatus = CivilStatus.getText();
        boolean key = false;
       
     
           
                  //Code in 1st form (Application Form) to transfer data in 2nd Form (ResultsApp) 
                  //Code in jButton
     
    
          
          
        /** CHECK FIRST IF USER HAS INPUT EVERYTHING **/
        if (firstName.equals("")) {
            JOptionPane.showMessageDialog(null, "FIRST NAME IS REQUIRED");
        }
        else if (middleName.equals("")) {
            JOptionPane.showMessageDialog(null, "MIDDLE NAME IS REQUIRED");
        }
        else if (lastName.equals("")) {
            JOptionPane.showMessageDialog(null, "LAST NAME IS REQUIRED");
        }
        else if (birthPlace.equals("")) {
            JOptionPane.showMessageDialog(null, "BIRTH PLACE IS REQUIRED");
        }
        else if (phoneNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "PHONE NUMBER IS REQUIRED");
        }
        else if (age.equals("")) {
            JOptionPane.showMessageDialog(null, "AGE IS REQUIRED"); 
        }    
        else if(Integer.valueOf(age)<=21||Integer.valueOf(age)>=60) {
            JOptionPane.showMessageDialog(null, "APPLICANTS BELOW 21 AND ABOVE 60 ARE NO APPLICABLE");
        }
        else if (civilStatus.equals("")) {
            JOptionPane.showMessageDialog(null, "CIVIL STATUS IS REQUIRED");
        }
        else if(!GenderMale.isSelected() && !GenderFemale.isSelected()) {
            JOptionPane.showMessageDialog(null, "GENDER IS REQUIRED");
        }
        else if(!YesPrior.isSelected() && !NoPrior.isSelected()) {
            JOptionPane.showMessageDialog(null, "PRIOR APPLICATION IS REQUIRED");   
        }
        else if(!NoPrior.isSelected()) {
            JOptionPane.showMessageDialog(null, "FAMILIES WITH PRIOR APPLCATION ARE NOT APPLICABLE");
        }
        else {
            JOptionPane.showMessageDialog(null, "VALIDATION SUCCESS!");
            key = true;
        }
        
        System.out.println(GenderMale);
        System.out.println(GenderFemale);    
        System.out.println(YesPrior);
        
        
        if(key==true) {
            ResultsApp x = new ResultsApp();
        
            ResultsApp.AddRowToJTable(new Object[]{
             JTextFieldFirstName.getText(),
             LastName.getText(),
             MiddleName.getText(),
             BirthPlace.getText(),
             PhoneNumber.getText(),
             Age.getText(),
             CivilStatus.getText(),
             gender
             });
             x.setVisible(true);
        }
    }//GEN-LAST:event_submitButton1ActionPerformed
   

    private void GenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderFemaleActionPerformed
        if (GenderFemale.isSelected()) {
            GenderMale.setSelected(false);
            gender = "Female";
        }
        
        
    }//GEN-LAST:event_GenderFemaleActionPerformed

    private void GenderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderMaleActionPerformed
        if (GenderMale.isSelected()) {
            GenderFemale.setSelected(false);
            gender="Male";
        }
        
        
    }//GEN-LAST:event_GenderMaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Age;
    public static javax.swing.JTextField BirthPlace;
    public static javax.swing.JTextField CivilStatus;
    public static javax.swing.JRadioButton GenderFemale;
    public static javax.swing.JRadioButton GenderMale;
    public static javax.swing.JTextField JTextFieldFirstName;
    public static javax.swing.JTextField LastName;
    public static javax.swing.JTextField MiddleName;
    public static javax.swing.JRadioButton NoPrior;
    public static javax.swing.JTextField PhoneNumber;
    public static javax.swing.JRadioButton YesPrior;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
private String gender;
}